---
title: "Appendix B: Data preparation"
output: word_document
---

Extracted data was cleaned, subfield categories added, and a subsample for testing and pre-registration purposes created. For each article, the following information was extracted: Digital Object Identifier(where available), raw text of the p-values (_e.g._ "$p=.048$"), sign of the p-value comparison ('>','<' or '='), the p-value itself, and finally the 200 characters immediately before the reported p-value, and the 200 characters immediately following. This data was collated into one large dataset containing 790,206 entries. From this dataset we removed a small number of entries (51) lacking identifying information, and all rows (1,073) where the p-values were not numerical (_e.g._ equal to '.'), due to misreporting or extraction-failure. Note that this does not include p-values that were misreported as too high (_e.g._ $p = 1.0$ instead of $p = .10$) or as possible p-values (_e.g._ $p = .99$ instead of $p = .099$). The values of interest here were those p-values most likely to be reported as marginally significant, and the dataset was next limited to only include these ($.05 < p <= .1$). This resulted in a final sample size of 50,891 p-values, originating from 19,875 articles, making up aout 6.4% of the original dataset. Subsequently, missing metadata (years and journal name) for 844 entries was retrieved from Crossref using the r-package 'rcrossref'. Following this, journal names were standardized for all entries, with older journals names updated to their current (2017) APA-names as per Appendix A, before adding subfield categories for each journal. Our categorization of journals into different subfields is taken from the APA's ([www.apa.org](www.apa.org)) divison of their journals into 'topics'. Note, however, that the APA allows the possibility of a journal belonging to several subfields. Finally, a stratified random sample (by journal) was taken from this finished dataset, containing approximately 6% of entries from each journal. This percentage was chosen to include data from a maximum amount of journals without the test-sample proportion growing too large. Five journals were not included in this test-sample due to consisting of too few entries (4 or fewer, _i.e._ necessitating a sample proportion of more than 25%). 
